# Generated by Django 5.2.12 on 2026-05-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={},
        ),
        migrations.RemoveField(
            model_name='property',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('residential', 'Residential'), ('business', 'Business / Commercial')], default='residential', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(default='available', max_length=20),
        ),
    ]
